[tool.poetry]
name = "final-project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numpy = "1.26"
opencv-python = "^4.9.0.80"
matplotlib = "^3.9.0"
scikit-learn = "^1.5.0"
